### ISSUE TITLE
Can't download Movie automatically

### ISSUE THREAD

**Issue by weekender23** [barbequesauce/Watcher3#140]
Hi

I am getting an error in the log.txt file which says "best title match was 50%, removing search result".  It seems that Watcher is not separating  the title name and the year of the movie. If i click the toggle rejected and accepted button i can see the movie but if i don't click the button i can't see the movie.

[log.txt](https://github.com/barbequesauce/Watcher3/files/4424760/log.txt)

**Comment by barbequesauce** [comment]
Looks like your size constraints are aggressive... the snippet below shows that the file size is too big....

```
INFO [2020-04-02 18:42:18,822] core.searchresults.score_sources.478: Filtering resolution and size requirements.
DEBUG [2020-04-02 18:42:18,823] core.searchresults.score_sources.489: Scoring and filtering Underwater.2020.BDRip.x264-WUTANG based on resolution BluRay-SD.
DEBUG [2020-04-02 18:42:18,823] core.searchresults.score_sources.507: Underwater.2020.BDRip.x264-WUTANG matches source BluRay-SD, checking size.
DEBUG [2020-04-02 18:42:18,823] core.searchresults.score_sources.489: Scoring and filtering Underwater.2020.1080p.BluRay.x264-WUTANG based on resolution BluRay-1080P.
DEBUG [2020-04-02 18:42:18,824] core.searchresults.score_sources.489: Scoring and filtering Underwater.2020.720p.BluRay.x264-WUTANG based on resolution BluRay-720P.
DEBUG [2020-04-02 18:42:18,824] core.searchresults.score_sources.507: Underwater.2020.720p.BluRay.x264-WUTANG matches source BluRay-720P, checking size.
DEBUG [2020-04-02 18:42:18,824] core.searchresults.score_sources.510: Removing Underwater.2020.720p.BluRay.x264-WUTANG, size 5452.003862 not in range 500-4500.
INFO [2020-04-02 18:42:18,825] core.searchresults.score_sources.523: Keeping 1 releases.
INFO [2020-04-02 18:42:18,825] core.searchresults.score_year.359: Checking year match.
INFO [2020-04-02 18:42:18,826] core.searchresults.fuzzy_title.393: Checking title match.
DEBUG [2020-04-02 18:42:18,826] core.searchresults.fuzzy_title.415: Comparing release substring Underwater 2020 with titles ['Underwater'].
```

**Comment by weekender23** [comment]
The movie that i am trying get is Underwater.2020.BDRip.x264-WUTANG (Blu-ray SD). I checked the size ranges in the quality section (50 min size and 7000 max size). It should have downloaded the movie.  Is this right for the title  'title': 'Underwater 2020' or should it be 'title': 'Underwater' 'year': 2020?

DEBUG [2020-04-02 18:42:18,795] core.searcher.search.156: Parse Underwater.2020.BDRip.x264-WUTANG
INFO [2020-04-02 18:42:18,795] core.searcher.get_source.350: Determining source media for {'quality': 'BDRip', 'codec': 'x264', 'group': 'WUTANG',}

thanks.

**Comment by barbequesauce** [comment]
'title': 'Underwater' 'year': 2020

What's the filename that you think should match?

**Comment by weekender23** [comment]
Sorry this what i wanted to paste on the last reply was cut off.

DEBUG [2020-04-02 18:42:18,795] core.searcher.search.156: Parse Underwater.2020.BDRip.x264-WUTANG
INFO [2020-04-02 18:42:18,795] core.searcher.get_source.350: Determining source media for {'quality': 'BDRip', 'codec': 'x264', 'group': 'WUTANG', 'title': 'Underwater 2020'}

Thats what i thought it should be 'title': 'Underwater' 'year': 2020 but watcher sees it as 'title': 'Underwater 2020'

**Comment by scambra** [comment]
PTN library had a regular expression to parse year which allowed years from 1900 to 2019, I have fixed to allow years until 2029

**Comment by weekender23** [comment]
The problem is still there. I added a new movie Arkansas 2020 and when I click on “Toggle rejected and accepted Results”, there’s an error: mismatch title (best match was 50%) (shown in the image).  When go into Settings -> Quality and uncheck “Score and filter release titles”, the movie will change from wanted to found.


![image](https://user-images.githubusercontent.com/33842064/80290982-660a7d00-86fe-11ea-859e-718cec87af01.png)

**Comment by weekender23** [comment]
thank you. That fixed my problem.
